application: dumbo
version: 1
runtime: python27
api_version: 1
threadsafe: off

handlers:
- url: /favicon\.ico
  static_files: client/img/favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: client/js

- url: /css
  static_dir: client/css

- url: /img
  static_dir: client/img

- url: .*
  script: server.main.app

libraries:
- name: webapp2
  version: "2.5.1"

