/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fauna_dumbo_Codegen */

#ifndef _Included_fauna_dumbo_Codegen
#define _Included_fauna_dumbo_Codegen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fauna_dumbo_Codegen
 * Method:    codegen
 * Signature: ([FI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fauna_dumbo_Codegen_codegen
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
